---
- name: apply windows update
  hosts: Client 
  gather_facts: no


  tasks:
    - name: check updates
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - DefinitionUpdates
          - UpdateRollups
        state: installed
        reboot: yes
        reboot_timeout: 600
       register: update_result

     - name: Display update summary
       debug: 
       msg: "{{ update_result }}"
