---
- name: apply windows update
  hosts: Client1 
  gather_facts: no
  collections:
    - ansible.windows

  tasks:
    - name: check updates
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        state: installed
        reboot: yes
        reboot_timeout: 600
      register: update_result

    - name: Display update summary
      debug: 
        var: update_result
